cache-size benchmark prototype
kponichtera/browser-cpu-fingerprinting-rs pull request #3
Opened 2023-03-16 20:14 UTC by Cornul11

2023-03-17 23:24 UTC, BuggStream commented on frontend/src/profilers/polyfills/instant.rs
> +    fn performance_now() -> f64;
I recommend just getting the window and getting access to the performance timer that way. Similar to how Cassie has done here: https://github.com/kponichtera/browser-cpu-fingerprinting-rs/compare/main...single-core#diff-3d7514b0fe68f9bfe81f4017b79dec4f6e0afcb8ef29f1303924393a459b7031R45

2023-03-18 19:37 UTC, Cornul11 commented on frontend/src/profilers/polyfills/instant.rs
> +    fn performance_now() -> f64;
I was initially doing the same way Cassie did, but thought some may find the possibility to write std-like code more convenient. We can leave it for those who want to use it that way for now. In case we find a way to mitigate this, we can remove it at later stages.

2023-03-21 11:51 UTC, kponichtera requested changes
Small remarks

2023-03-21 11:51 UTC, kponichtera commented on frontend/src/profilers/mod.rs
> +    pub mod instant;
Defining the modules like this can easily make their hierarchy messy to follow, imo. It'd be better to create `polyfills` directory with `mod.rs` and `instant.rs` files inside, and export `pub mod instant` in `mod.rs`.

2023-03-21 11:51 UTC, kponichtera commented on frontend/src/profilers/polyfills/instant.rs
> +#[cfg(not(target_arch = "wasm32"))]
Frontend is compiled only to WASM, we don't need code for different architectures.

2023-03-22 10:15 UTC, BuggStream approved these changes

2023-03-22 12:49 UTC, kponichtera approved these changes

2023-03-22 12:50 UTC, merged